// The page bundle's view of the config, generated by the Vite plugin (`./vite.ts`).
declare module 'virtual:xcwds/client' {
	/** Each plugin's `./client` entry with its options from the config. */
	export const plugins: [import('@xcwds/core').Plugin<never>, Record<string, unknown>][];
	export const data: import('./data.js').ClientData;
}
