// Decision 4: app.html is a static template, so the pre-paint script goes in here. This runs
// at prerender time, including for the 404.html fallback.
import type { Handle } from '@sveltejs/kit';
// Generated by spike/xcwds.js when svelte.config.js loads.
import { head } from '../.xcwds/head.js';

export const handle: Handle = ({ event, resolve }) =>
	resolve(event, { transformPageChunk: ({ html }) => html.replace('%xcwds.head%', head) });
