/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />
// Decision 3: plugins' worker entries arrive through a generated file, not a virtual module.
// Generated by spike/xcwds.js when svelte.config.js loads.
import { plugins } from '../.xcwds/worker.js';

type FetchHook = (url: URL, options: unknown) => Response | undefined;
const sw = self as unknown as ServiceWorkerGlobalScope;

sw.addEventListener('install', () => void sw.skipWaiting());
sw.addEventListener('activate', (event) => event.waitUntil(sw.clients.claim()));

sw.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);
	if (event.request.method !== 'GET' || url.origin !== sw.location.origin) return;
	// Like Fastify's onRequest: the first hook that returns a Response answers the request.
	for (const [hooks, options] of plugins as [{ onFetch?: FetchHook }, unknown][]) {
		const response = hooks.onFetch?.(url, options);
		if (response) return event.respondWith(response);
	}
});
