// Writes src/versions.ts: the version ranges a new app depends on, taken from this monorepo so
// they never drift: each @xcwds package's own version, and the third-party versions
// examples/minimal and the root use (the generated app is checked against the same).
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../../../', import.meta.url).pathname;
const read = (file) => JSON.parse(readFileSync(join(root, file), 'utf8'));

const xcwds = {};
for (const dir of readdirSync(join(root, 'packages'))) {
	const file = join('packages', dir, 'package.json');
	if (!existsSync(join(root, file))) continue;
	const { name, version } = read(file);
	xcwds[name] = version;
}
const example = read('examples/minimal/package.json');
const monorepo = read('package.json');
const thirdParty = { ...monorepo.devDependencies, ...example.devDependencies };
for (const name of Object.keys(thirdParty)) if (name.startsWith('@xcwds/')) delete thirdParty[name];

const source = `// Generated by scripts/versions.js when the package builds. Do not edit.
export const XCWDS_VERSIONS: Record<string, string> = ${JSON.stringify(xcwds, null, '\t')};

export const THIRD_PARTY_VERSIONS: Record<string, string> = ${JSON.stringify(thirdParty, null, '\t')};
`;
const out = new URL('../src/versions.ts', import.meta.url);
if (!existsSync(out) || readFileSync(out, 'utf8') !== source) writeFileSync(out, source);
